# 1. 교차 검증과 그리드서치


# 1.1 검증세트

In [1]:
import pandas as pd
wine = pd.read_csv('https://bit.ly/wine_csv_data')

In [2]:
X_data=wine.drop(["class"],axis=1).to_numpy() #X_data=wine[["alcohol","sugar",0"pH"]]
Y_data=wine["class"].to_numpy()

In [3]:
from sklearn.model_selection  import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X_data,Y_data,test_size=0.2,random_state=42)

In [4]:
S_train,S_text,Z_train,Z_test=train_test_split(X_train,Y_train,test_size=0.2,random_state=42)

In [5]:
print(S_train.shape,Z_test.shape)

(4157, 3) (1040,)


In [6]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(S_train,Z_train)
print(dt.score(S_train,Z_train))
print(dt.score(S_text,Z_test))

0.9971133028626413
0.8653846153846154


# 1.2 교차검증

In [8]:
from sklearn.model_selection import cross_validate
scores=cross_validate(dt,X_train,Y_train)
print(scores)

{'fit_time': array([0.00698042, 0.00615978, 0.        , 0.01170588, 0.        ]), 'score_time': array([0.0009973, 0.       , 0.       , 0.       , 0.       ]), 'test_score': array([0.86730769, 0.85384615, 0.87391723, 0.85466795, 0.84215592])}


In [9]:
import numpy as np
print(np.mean(scores["test_score"]))

0.8583789886725401


# 분할기를 사용한 교차검증

In [10]:

from sklearn.model_selection import StratifiedKFold
scores=cross_validate(dt,X_train,Y_train)
print(np.mean(scores["test_score"]))

0.8574178203894277


In [11]:
splitters=StratifiedKFold(n_splits=10,shuffle=True,random_state=42)
scores=cross_validate(dt,X_train,Y_train)
print(np.mean(scores["test_score"]))

0.857224587251055


# 3. 하이퍼라미터 튜닝

In [13]:
from sklearn.model_selection import GridSearchCV
params={'min_impurity_decrease':[0.0001,0.0002,0.0003,0.0004,0.00005]}

In [14]:
gs=GridSearchCV(DecisionTreeClassifier(random_state=42),params,n_jobs=-1)

for params in[0.0001,0.0002,0.0003,0.0004,0.00005]:
    gs=GridSearchCV(DecisionTreeClassifier(random_state=42),params,n_jobs=-1)
    gs.fit(X_train,Y_train)
    socres=gs.score(X_train,Y_train)
    print(scores)

In [ ]:
for 0.001,00.001

In [15]:
gs.fit(X_train,Y_train)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'min_impurity_decrease': [0.0001, 0.0002, 0.0003,
                                                   0.0004, 5e-05]})

In [16]:
dt=gs.best_estimator_
print(dt.score(X_train,Y_train))

0.9615162593804117


In [17]:
print(gs.best_estimator_)

DecisionTreeClassifier(min_impurity_decrease=0.0001, random_state=42)


In [18]:
print(gs.best_params_)

{'min_impurity_decrease': 0.0001}


In [19]:
print(gs.cv_results_["mean_test_score"])

[0.86819297 0.86453617 0.86492226 0.86780891 0.86126527]


In [20]:
best_index=np.argmax(gs.cv)

In [21]:
best_index=np.argmax(gs.cv)
print(gs.cv_results_["params"],[best_index])

[{'min_impurity_decrease': 0.0001}, {'min_impurity_decrease': 0.0002}, {'min_impurity_decrease': 0.0003}, {'min_impurity_decrease': 0.0004}, {'min_impurity_decrease': 5e-05}] [0]


In [36]:
params={'min_impurity_decrease':np.arange(0.0001,0.001,0.0001),
         "max_depth":range(5,20,1), 
          "min_samples_split" :range(2,100,10)}

In [37]:
gs=GridSearchCV(DecisionTreeClassifier(random_state=42),params,n_jobs=-1)

In [38]:
gs.fit(X_train,Y_train)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': range(5, 20),
                         'min_impurity_decrease': array([0.0001, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007, 0.0008,
       0.0009]),
                         'min_samples_split': range(2, 100, 10)})

In [39]:
print(gs.cv_results_["mean_test_score"])

[0.85780355 0.85799604 0.85799604 ... 0.86126601 0.86165063 0.86357629]


In [40]:
print(gs.best_params_)

{'max_depth': 14, 'min_impurity_decrease': 0.0004, 'min_samples_split': 12}


In [ ]:
for x in[0.0001,0.001,0.0001]:
    for y in range[5,20,1]:
        forz in range[2,100,10]:
            gs=GridSearchCV(DecisionTreeClassifier(random_state=42, )
             

# 3.1 렌덤서치

In [45]:
from scipy.stats import uniform,randint

In [50]:
rgen=randint(0,10)
rgen.rvs(10)

array([4, 8, 8, 1, 1, 4, 9, 8, 8, 7], dtype=int64)

In [49]:
np.unique(rgen.rvs(1000),return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),
 array([109, 105,  86, 111,  98,  93, 111, 101,  87,  99], dtype=int64))

In [51]:
rgen=uniform(0,1)
np.unique(rgen.rvs(1000),return_counts=True)

(array([0.00188376, 0.00352134, 0.00523988, 0.00596797, 0.00633261,
        0.00718219, 0.00902364, 0.00941144, 0.01019619, 0.01164517,
        0.01203236, 0.01279333, 0.01607803, 0.01656046, 0.01805733,
        0.01830918, 0.0186887 , 0.01902034, 0.02152247, 0.02160535,
        0.02240942, 0.02291002, 0.02324311, 0.02593712, 0.02661669,
        0.02766423, 0.02856043, 0.02958345, 0.02984717, 0.03038843,
        0.03340183, 0.03408462, 0.03533167, 0.03575936, 0.03591815,
        0.03667515, 0.03842815, 0.03861753, 0.03889302, 0.03896149,
        0.04093002, 0.04164058, 0.04458099, 0.04904351, 0.04908112,
        0.05147376, 0.05154941, 0.05219243, 0.05440942, 0.055066  ,
        0.05509722, 0.05576944, 0.05672312, 0.05806526, 0.05928673,
        0.05995409, 0.06054374, 0.06392121, 0.06392985, 0.06397327,
        0.06679049, 0.06969494, 0.07011436, 0.07180952, 0.07256866,
        0.0750875 , 0.07689671, 0.07729192, 0.07781086, 0.07816945,
        0.07948922, 0.08093488, 0.08096394, 0.08

In [56]:
params = {"min_impurity_decrease": uniform(0.0001, 0.001),
          "max_depth" : randint(20, 50),
          "min_samples_split" : range(2, 25),
          "min_samples_leaf" : range(1, 25),
          }

In [57]:
from sklearn.model_selection import RandomizedSearchCV

In [58]:
gs=RandomizedSearchCV(DecisionTreeClassifier(random_state=42),params,n_iter=100,n_jobs=1,
                      random_state=42)
gs.fit(X_train,Y_train)

RandomizedSearchCV(estimator=DecisionTreeClassifier(random_state=42),
                   n_iter=100, n_jobs=1,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001484A76FAF0>,
                                        'min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000001484A75B340>,
                                        'min_samples_leaf': range(1, 25),
                                        'min_samples_split': range(2, 25)},
                   random_state=42)