 # 1.1 렌덤포레스트

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection  import train_test_split
wine = pd.read_csv('https://bit.ly/wine_csv_data')
X_data=wine.drop(["class"],axis=1).to_numpy() 
Y_data=wine["class"].to_numpy()
X_train,X_test,Y_train,Y_test=train_test_split(X_data,Y_data,test_size=0.2,random_state=42)

In [5]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_jobs=-1,random_state=42)
scores=cross_validate(rf,X_train,Y_train,return_train_score=True,n_jobs=-1)
print(np.mean(scores["train_score"]),np.mean(scores["test_score"]))

0.9973541965122431 0.8905151032797809


In [19]:
rf.fit(X_train,Y_train)
print(rf.feature_importances_)

[0.23167441 0.50039841 0.26792718]


In [21]:
rf = RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=42)
rf.fit(X_train,Y_train)
print(rf.oob_score_)

0.8934000384837406


# 1.2엑소스트라 트리(부트스트랩 샘플을 사용하지 않는다)

In [17]:
from sklearn.ensemble import ExtraTreesClassifier
ef=ExtraTreesClassifier(n_jobs=-1,random_state=42)
scores=cross_validate(rf,X_train,Y_train,return_train_score=True,n_jobs=-1)
print(np.mean(scores["train_score"]),np.mean(scores["test_score"]))

0.9973541965122431 0.8905151032797809


In [18]:
rf.fit(X_train,Y_train)
print(rf.feature_importances_)

[0.23167441 0.50039841 0.26792718]


# 1.3 그레이디언트 부스팅

In [23]:
from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier(random_state=42)
scores=cross_validate(gb,X_train,Y_train,return_train_score=True,n_jobs=-1)
print(np.mean(scores["train_score"]),np.mean(scores["test_score"]))

0.8881086892152563 0.8720430147331015


In [35]:

from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier(n_estimators=500,random_state=42)
scores=cross_validate(gb,X_train,Y_train,return_train_score=True,n_jobs=-1)
print(np.mean(scores["train_score"]),np.mean(scores["test_score"]))

0.9215896435285418 0.8749283704745687


In [26]:
gb.fit(X_train,Y_train)
print(gb.feature_importances_)

[0.14230296 0.70606994 0.1516271 ]


# 1.4 히스토그램 기반 부스팅

In [36]:
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingClassifier
hgd=HistGradientBoostingClassifier(random_state=42)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9215896435285418 0.8749283704745687


In [44]:
from sklearn.inspection import permutation_importance
hgd.fit(X_train,Y_train)
result=permutation_importance(hgd,X_train,Y_train,n_repeats=10,random_state=42,n_jobs=-1)
print(result.importances_mean)

[0.08876275 0.23438522 0.08027708]


In [45]:
hgd.score(X_test,Y_test)

0.8723076923076923

In [53]:
from xgboost import XGBClassifier

xgb = XGBClassifier(tree_method='hist', random_state=42)
scores = cross_validate(xgb, X_train, Y_train, return_train_score=True, n_jobs=-1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9555033709953124 0.8799326275264677


In [54]:
from lightgbm import LGBMClassifier
lgb=LGBMClassifier(random_state=42)
scores = cross_validate(xgb, X_train, Y_train, return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9555033709953124 0.8799326275264677
