In [25]:
data=[[1,2,3,4,5],[11,12,13,14,15],[16,17,18,19,20]]

In [24]:
data

[[1, 2, 3, 4, 5], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20, 21]]

In [26]:
data2=np.array(data)

In [5]:
import numpy as np

In [27]:
data2.shape

(3, 5)

In [21]:
data2[2]=100

In [28]:
data2

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [31]:
data2=data2.ravel()

In [32]:
data2.shape

(15,)

In [33]:
data2.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [35]:
data2.T #(3,5)=(5,3)

array([ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [44]:
a=np.arange(1,11).reshape(5,2)
b=np.array([[1,1,0],[0,1,1]])

In [46]:
np.matmul(a,b),np.dot(a,b)

(array([[ 1,  3,  2],
        [ 3,  7,  4],
        [ 5, 11,  6],
        [ 7, 15,  8],
        [ 9, 19, 10]]),
 array([[ 1,  3,  2],
        [ 3,  7,  4],
        [ 5, 11,  6],
        [ 7, 15,  8],
        [ 9, 19, 10]]))

In [49]:
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[7,8,9], [10,11,12]])

In [56]:
a@b

array([[ 1,  3,  2],
       [ 3,  7,  4],
       [ 5, 11,  6],
       [ 7, 15,  8],
       [ 9, 19, 10]])

In [55]:
b

array([[1, 1, 0],
       [0, 1, 1]])